# One Hot Encoding

one hot encoding is used to encode categorical data and working as follow:
for each catecorial or word of data convert to integer number but binarry classifcation and each word is 0 or 1.

Then, each integer value is represented as a binary vector that is all zero values except the index of the integer, which is marked with a 1.
also one hot encoding encode in such away:
- words represent each words even those which are repeated
- but columns represent unique words of our corps

### one hot is used for categorical data like colors = 'red', 'green'

In [1]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import itertools
import sys
import os
sys.path.append(os.path.abspath('../scraping_cleaning'))
from cleaning_data import *

Our scraped now are 5777 Product
one product Data

 {'_id': ObjectId('5e48539b980cc3c34837af7f'), 'product_title': 'هاتف ابل ايفون 11 مع فيس تايم بشريحة واحدة وشريحة الكترونية - ذاكرة تخزين 64 جيجا، ذاكرة وصول عشوائية 4 جيجا، شبكة ال تي اي من الجيل الرابع - ارجواني', 'product_url': 'https://egypt.souq.com/eg-ar/%D9%87%D8%A7%D8%AA%D9%81-%D8%A7%D8%A8%D9%84-%D8%A7%D9%8A%D9%81%D9%88%D9%86-11-%D9%85%D8%B9-%D9%81%D9%8A%D8%B3-%D8%AA%D8%A7%D9%8A%D9%85-%D8%A8%D8%B4%D8%B1%D9%8A%D8%AD%D8%A9-%D9%88%D8%A7%D8%AD%D8%AF%D8%A9-%D9%88%D8%B4%D8%B1%D9%8A%D8%AD%D8%A9-%D8%A7%D9%84%D9%83%D8%AA%D8%B1%D9%88%D9%86%D9%8A%D8%A9-%D8%B0%D8%A7%D9%83%D8%B1%D8%A9-%D8%AA%D8%AE%D8%B2%D9%8A%D9%86-64-%D8%AC%D9%8A%D8%AC%D8%A7-%D8%B0%D8%A7%D9%83%D8%B1%D8%A9-%D9%88%D8%B5%D9%88%D9%84-%D8%B9%D8%B4%D9%88%D8%A7%D8%A6%D9%8A%D8%A9-4-%D8%AC%D9%8A%D8%AC%D8%A7-%D8%B4%D8%A8%D9%83%D8%A9-%D8%A7%D9%84-%D8%AA%D9%8A-%D8%A7%D9%8A-%D9%85%D9%86-%D8%A7%D9%84%D8%AC%D9%8A%D9%84-%D8%A7%D9%84%D8%B1%D8%A7%D8%A8%D8%B9-%D8%A7%D8%B1%D8%AC%D9%88%D8%A7%D9%86%D9%8A-68312948/i/', 'image_src': 'https://cf1.s3.souqcdn.com/item/2019/09/12/68/31/29/48/item_L_68312948_63bd51c18418a.jpg', 'product_new_price': 14299.0, 'product_old_price': 0.0, 'product_discount_percentage': 0.0, 'product_discount_value': 0.0, 'product_reviews': ['جهاز رائع', 'ممتاز', 'جهاز ما يحتاج تقييم', 'توصيل سريع وسعر ممتاز', 'السلام عليكم ورحمة الله وبركاته لقد تم إيصال الجوال الايفون ولم تصلني الشريحة الإلكترونية أرجو الإفادة', 'ممتاز والتوصيل مره سريع', 'كل شئ يجنن تغليف ممتاز توصيل سريع سعر رائع شكرا سوق', 'شكرا السعر وربي ببلاش كمان وصل سريع', 'المنتج أصلي وسعره منافس وأقل من التطبيقات الأخرى المنتج أصلي وسعره منافس وأقل من التطبيقات الأخرى المنتج أصلي وسعره منافس وأقل من التطبيقات الأخرى', 'لا يوجد', 'Loved', 'يعطيهم العافيه الجهاز وصل سليم وممتاز', 'ممتاز جدا', 'مطابق للمواصفات و سرعه فى التوصيل', 'مثل ما هو مكتوب والتوصيل في الموعد', 'جميييييل', 'ممتاز والسعر كويس', 'رائع', 'صراحة كنت خايفة يطلع مو اصلي لكن الحمدلله طلع اصلي١٠٠٪\u061c والسعر منافس جدا', 'جميل', 'ممتاز', 'هاتف جميل وأنيق', 'صراحه جوده فاشله جدا', 'منتج اصلي وتوصيل رائع', 'جميل جدا انصح به', 'ممتاز', 'ممتاز جدا وسرعه بخدمة الشحن', 'شكرا لسوق ع السعر الرايع', 'المنتج اصلي ولا يوجد اي ملاحظات وتم توصيله بسرعة شكراً', 'ممتاز', 'الجهاز معروف والتوصيل في الموعد شكراً لكم', 'السعر كان جداً جميل ، التوصيل سريع', 'perfect and delivered within 1 day', 'Good', 'Just changed from Samsung s9 to this , so good to be an iPhone user, build quality is excellent', 'Original .. Thanks', 'السعر رائع والتوصيل سريع جدا', 'At first I was so worried and suspicious, but once it arrived I checked the serial number and it’s as original as it can be, very good, packaging was well done, and the device is amazing', 'I love it and delivery is too fast', 'وصل تاني يوم من الطلب شكرا سوق'], 'main_feature_of_product': ['2019-09-13', '16.4 centimeters', '512 grams', '190199222397', 'ابل', 'iOS', '64 جيجابايت', 'Dual SIM (nano-SIM and eSIM)', 'هواتف ذكية', '4جي ال تي اي', 'ابل', 'MWLX2AH/A', '2000 - 3000 مللي أمبير_ساعة', 'UPC-A', '190199222397', '2724968977898', '12MP Ultra Wide + 12 MP Wide', '6.1 انش', 'ارجواني', '4 جيجابايت'], 'Uploaded_product': False}
First File
 156

After Expanding two file together
 889

Remove Dublicated words
 661

Update the end file manually to remove some of words
 525
Total Arabic reviews
 38695

Total English reviews
 34166

Some of  Arabic reviews
 ['جهاز ممتاز و تسليم من سوق فوق الممتاز', 'ممتاز شكراً لسوق كوم وللبائع وتوصيل سريع أيضا', 'شيء خرافي', 'ابداع جديد من سامسونج', 'لايوجد']

some of English reviews
 ['I love it', 'soug really doing good service to society | compare to the local market the prices are very less - minimum 5%', 'Faster delivery ,genuine product. ..Cheaper in price as compare to any other online shopping. Must try this seller...Thanks Souq..', 'Genuine Product', 'Nothing']
Now Total Arabic reviews
 20494

Now Total English reviews
 18950
Now Total Arabic reviews
 19870

Now Total English reviews
 18220

### Example of one hot encoding without library "Manual One Hot Encoding"

Function below take an argument as string like "I am learning NLP"
and return one hot encoding example like:

![one_hot_encoding](../images/one_hot_encoding.png "one_hot_encoding")

In [2]:
def convert_string_to_one_hot_manual(text):
    '''
    Argument:
        text as string
    return:
        one hot encoding data frame
    '''
    one_hot_encoding = []
    text_list = text.split() # covert string to list
# make each word as key and integer as value
    text_words_as_key = dict((c,i) for i,c in enumerate(text_list))
    for key,val in enumerate(text_list):
        
# list of zeros and for each word will assign one and everyone else 0
        words = [0 for i in text_list]
    
# assign one for the word in our dictionary
        words[text_words_as_key[val]] = 1
    
# append this one_hot_word vector
        one_hot_encoding.append(words)
    
    one_hot_encoding = pd.DataFrame(one_hot_encoding, columns=text_list)
    return one_hot_encoding

In [3]:
def convert_string_to_one_hot_using_pannds(text):
    '''
    Argument:
        text as string
    return:
        apply one hot encoding on text
    '''
    text_list = text.split() # covert string to list
    print(len(text_list))
    one_hot_encoding = pd.get_dummies(text_list) # using pandas
    
    return one_hot_encoding

## One-Hot Encoding using sklearn
**To convert  one hot with sklearn you first convert to label encoding.**

In [4]:
def convert_string_to_labelencoder_using_sklearn(text):
    '''
    Argument:
        function take list of strings:
        first convert these strings to list of all words of these string
        second apply sklearn to one-hot-encoding
     return: hot
    '''
# using function from data cleaning to convert the list of strings
    text = convert_list_of_strings_to_list_of_words(text)

# convert to data frame of pandas
    text = pd.DataFrame(text, columns=['reviews_words'])
# creating instance object from labelencoder
    labelencoder = LabelEncoder()
    text['labels_encode'] = labelencoder.fit_transform(text['reviews_words'])
    return text

In [5]:
text = convert_string_to_labelencoder_using_sklearn(all_arabic_reviews)
text

       reviews_words  labels_encode
0               سرعة          10291
1            التوصيل           3767
2               ونفس          18413
3          المواصفات           5614
4               جيدة           9197
...              ...            ...
145934        اجمالا           2159
145935         ممتاز          14921
145936         وانصح          16624
145937       بالشراء           6526
145938           جدا           8870

[145939 rows x 2 columns]

### convert to one hot
**function above convert first to label encoding then we convert to one hot encoding.**

Though label encoding is straight way but it has the disadvantage that the numeric values can be misinterpreted by algorithms as having some sort of hierarchy/order as above.

OneHotEncoder from SciKit library only takes numerical categorical values, hence any value of string type should be label encoded before one hot encoded. So taking the dataframe from the previous example, we will apply OneHotEncoder.

In [6]:
def convert_string_to_one_hot_using_sklearn(text):
    '''
    Argument:
        dataframe from the previous example
    return:
        apply OneHotEncoder on column 
        
    '''
    one_hot_encod = OneHotEncoder()
    one_hot_encod = pd.DataFrame(one_hot_encod.fit_transform(text[['labels_encode']]).toarray(), dtype=int)
    return one_hot_encod

In [7]:
one_hot_encod = convert_string_to_one_hot_using_sklearn(text[:10])
one_hot_encod

/home/abdelrahman/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)

   0  1  2  3  4  5  6  7  8  9
0  0  0  0  0  1  0  0  0  0  0
1  1  0  0  0  0  0  0  0  0  0
2  0  0  0  0  0  0  0  0  0  1
3  0  1  0  0  0  0  0  0  0  0
4  0  0  0  1  0  0  0  0  0  0
5  0  0  0  0  0  0  0  0  1  0
6  0  0  0  0  0  0  1  0  0  0
7  0  0  0  0  0  0  0  1  0  0
8  0  0  1  0  0  0  0  0  0  0
9  0  0  0  0  0  1  0  0  0  0